export interface ServiceConfig {
  name: string;
  slug: string;
  category: string;
  statusPageUrl: string;
  apiEndpoint: string;
  sourceType: "STATUSPAGE_API" | "AWS_HEALTH" | "GCP_STATUS" | "AZURE_HTML";
  logoUrl?: string;
}

export const services: ServiceConfig[] = [
  // --- Version Control & CI/CD ---
  {
    name: "GitHub",
    slug: "github",
    category: "Version Control & CI/CD",
    statusPageUrl: "https://www.githubstatus.com",
    apiEndpoint: "https://www.githubstatus.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://github.githubassets.com/favicons/favicon-dark.svg",
  },
  {
    name: "GitLab",
    slug: "gitlab",
    category: "Version Control & CI/CD",
    statusPageUrl: "https://status.gitlab.com",
    apiEndpoint: "https://status.gitlab.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://gitlab.com/favicon.ico",
  },
  {
    name: "Bitbucket",
    slug: "bitbucket",
    category: "Version Control & CI/CD",
    statusPageUrl: "https://bitbucket.status.atlassian.com",
    apiEndpoint: "https://bitbucket.status.atlassian.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://bitbucket.org/favicon.ico",
  },
  {
    name: "CircleCI",
    slug: "circleci",
    category: "Version Control & CI/CD",
    statusPageUrl: "https://status.circleci.com",
    apiEndpoint: "https://status.circleci.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://circleci.com/favicon.ico",
  },

  // --- Cloud & Hosting ---
  {
    name: "Vercel",
    slug: "vercel",
    category: "Cloud & Hosting",
    statusPageUrl: "https://www.vercel-status.com",
    apiEndpoint: "https://www.vercel-status.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://assets.vercel.com/image/upload/front/favicon/vercel/favicon.ico",
  },
  {
    name: "Netlify",
    slug: "netlify",
    category: "Cloud & Hosting",
    statusPageUrl: "https://www.netlifystatus.com",
    apiEndpoint: "https://www.netlifystatus.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://www.netlify.com/favicon/icon.svg",
  },
  {
    name: "Heroku",
    slug: "heroku",
    category: "Cloud & Hosting",
    statusPageUrl: "https://status.heroku.com",
    apiEndpoint: "https://status.heroku.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://www.herokucdn.com/favicons/favicon.ico",
  },
  {
    name: "Render",
    slug: "render",
    category: "Cloud & Hosting",
    statusPageUrl: "https://status.render.com",
    apiEndpoint: "https://status.render.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://render.com/icon.svg",
  },
  {
    name: "Railway",
    slug: "railway",
    category: "Cloud & Hosting",
    statusPageUrl: "https://status.railway.app",
    apiEndpoint: "https://status.railway.app/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://railway.app/favicon.ico",
  },
  {
    name: "DigitalOcean",
    slug: "digitalocean",
    category: "Cloud & Hosting",
    statusPageUrl: "https://status.digitalocean.com",
    apiEndpoint: "https://status.digitalocean.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://www.digitalocean.com/_next/static/media/favicon-32x32.b7ef9ede.png",
  },

  // --- Cloud Providers (Custom) ---
  {
    name: "AWS",
    slug: "aws",
    category: "Cloud Providers",
    statusPageUrl: "https://status.aws.amazon.com",
    apiEndpoint: "https://health.aws.amazon.com/public/currentevents",
    sourceType: "AWS_HEALTH",
    logoUrl: "https://a0.awsstatic.com/libra-css/images/site/fav/favicon.ico",
  },
  {
    name: "Google Cloud",
    slug: "gcp",
    category: "Cloud Providers",
    statusPageUrl: "https://status.cloud.google.com",
    apiEndpoint: "https://status.cloud.google.com/incidents.json",
    sourceType: "GCP_STATUS",
    logoUrl: "https://cloud.google.com/favicon.ico",
  },
  {
    name: "Microsoft Azure",
    slug: "azure",
    category: "Cloud Providers",
    statusPageUrl: "https://azure.status.microsoft",
    apiEndpoint: "https://azure.status.microsoft/en-us/status",
    sourceType: "AZURE_HTML",
    logoUrl: "https://azure.microsoft.com/favicon.ico",
  },

  // --- Databases ---
  {
    name: "MongoDB Atlas",
    slug: "mongodb",
    category: "Databases",
    statusPageUrl: "https://status.cloud.mongodb.com",
    apiEndpoint: "https://status.cloud.mongodb.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://www.mongodb.com/assets/images/global/favicon.ico",
  },
  {
    name: "Supabase",
    slug: "supabase",
    category: "Databases",
    statusPageUrl: "https://status.supabase.com",
    apiEndpoint: "https://status.supabase.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://supabase.com/favicon/favicon-196x196.png",
  },
  {
    name: "PlanetScale",
    slug: "planetscale",
    category: "Databases",
    statusPageUrl: "https://www.planetscalestatus.com",
    apiEndpoint: "https://www.planetscalestatus.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://planetscale.com/favicon.ico",
  },

  // --- Payments ---
  {
    name: "Stripe",
    slug: "stripe",
    category: "Payments",
    statusPageUrl: "https://status.stripe.com",
    apiEndpoint: "https://status.stripe.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://stripe.com/favicon.ico",
  },
  {
    name: "Shopify",
    slug: "shopify",
    category: "Payments",
    statusPageUrl: "https://www.shopifystatus.com",
    apiEndpoint: "https://www.shopifystatus.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://cdn.shopify.com/static/shopify-favicon.png",
  },

  // --- Communication ---
  {
    name: "Twilio",
    slug: "twilio",
    category: "Communication",
    statusPageUrl: "https://status.twilio.com",
    apiEndpoint: "https://status.twilio.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://www.twilio.com/favicon.ico",
  },
  {
    name: "SendGrid",
    slug: "sendgrid",
    category: "Communication",
    statusPageUrl: "https://status.sendgrid.com",
    apiEndpoint: "https://status.sendgrid.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://sendgrid.com/favicon.ico",
  },
  {
    name: "Mailgun",
    slug: "mailgun",
    category: "Communication",
    statusPageUrl: "https://status.mailgun.com",
    apiEndpoint: "https://status.mailgun.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://www.mailgun.com/favicon.ico",
  },

  // --- Productivity ---
  {
    name: "Slack",
    slug: "slack",
    category: "Productivity",
    statusPageUrl: "https://status.slack.com",
    apiEndpoint: "https://status.slack.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://a.slack-edge.com/80588/marketing/img/meta/favicon-32.png",
  },
  {
    name: "Zoom",
    slug: "zoom",
    category: "Productivity",
    statusPageUrl: "https://status.zoom.us",
    apiEndpoint: "https://status.zoom.us/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://zoom.us/favicon.ico",
  },
  {
    name: "Figma",
    slug: "figma",
    category: "Productivity",
    statusPageUrl: "https://status.figma.com",
    apiEndpoint: "https://status.figma.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://static.figma.com/app/icon/1/favicon.png",
  },
  {
    name: "Notion",
    slug: "notion",
    category: "Productivity",
    statusPageUrl: "https://status.notion.so",
    apiEndpoint: "https://status.notion.so/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://www.notion.so/images/favicon.ico",
  },
  {
    name: "Jira",
    slug: "jira",
    category: "Productivity",
    statusPageUrl: "https://jira-software.status.atlassian.com",
    apiEndpoint: "https://jira-software.status.atlassian.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://jira.atlassian.com/favicon.ico",
  },
  {
    name: "Confluence",
    slug: "confluence",
    category: "Productivity",
    statusPageUrl: "https://confluence.status.atlassian.com",
    apiEndpoint: "https://confluence.status.atlassian.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://confluence.atlassian.com/favicon.ico",
  },

  // --- CDN & Performance ---
  {
    name: "Cloudflare",
    slug: "cloudflare",
    category: "CDN & Performance",
    statusPageUrl: "https://www.cloudflarestatus.com",
    apiEndpoint: "https://www.cloudflarestatus.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://www.cloudflare.com/favicon.ico",
  },
  {
    name: "Cloudinary",
    slug: "cloudinary",
    category: "CDN & Performance",
    statusPageUrl: "https://status.cloudinary.com",
    apiEndpoint: "https://status.cloudinary.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://cloudinary.com/favicon.ico",
  },
  {
    name: "Imgix",
    slug: "imgix",
    category: "CDN & Performance",
    statusPageUrl: "https://status.imgix.com",
    apiEndpoint: "https://status.imgix.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://imgix.com/favicon.ico",
  },

  // --- Monitoring ---
  {
    name: "Datadog",
    slug: "datadog",
    category: "Monitoring",
    statusPageUrl: "https://status.datadoghq.com",
    apiEndpoint: "https://status.datadoghq.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://www.datadoghq.com/favicon.ico",
  },
  {
    name: "New Relic",
    slug: "newrelic",
    category: "Monitoring",
    statusPageUrl: "https://status.newrelic.com",
    apiEndpoint: "https://status.newrelic.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://newrelic.com/favicon.ico",
  },
  {
    name: "Sentry",
    slug: "sentry",
    category: "Monitoring",
    statusPageUrl: "https://status.sentry.io",
    apiEndpoint: "https://status.sentry.io/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://www.google.com/s2/favicons?domain=sentry.io&sz=64",
  },
  {
    name: "PagerDuty",
    slug: "pagerduty",
    category: "Monitoring",
    statusPageUrl: "https://status.pagerduty.com",
    apiEndpoint: "https://status.pagerduty.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://www.pagerduty.com/favicon.ico",
  },

  // --- Auth & Identity ---
  {
    name: "Auth0",
    slug: "auth0",
    category: "Auth & Identity",
    statusPageUrl: "https://status.auth0.com",
    apiEndpoint: "https://status.auth0.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://cdn2.auth0.com/styleguide/latest/lib/logos/img/favicon.png",
  },
  {
    name: "Okta",
    slug: "okta",
    category: "Auth & Identity",
    statusPageUrl: "https://status.okta.com",
    apiEndpoint: "https://status.okta.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://www.okta.com/favicon.ico",
  },

  // --- AI & ML ---
  {
    name: "OpenAI",
    slug: "openai",
    category: "AI & ML",
    statusPageUrl: "https://status.openai.com",
    apiEndpoint: "https://status.openai.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://www.google.com/s2/favicons?domain=openai.com&sz=64",
  },
  {
    name: "Anthropic",
    slug: "anthropic",
    category: "AI & ML",
    statusPageUrl: "https://status.anthropic.com",
    apiEndpoint: "https://status.anthropic.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://www.google.com/s2/favicons?domain=anthropic.com&sz=64",
  },

  // --- Developer Tools ---
  {
    name: "Postman",
    slug: "postman",
    category: "Developer Tools",
    statusPageUrl: "https://status.postman.com",
    apiEndpoint: "https://status.postman.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://www.postman.com/_mk-www-next/icons/favicon-32x32.png",
  },
  {
    name: "npm",
    slug: "npm",
    category: "Developer Tools",
    statusPageUrl: "https://status.npmjs.org",
    apiEndpoint: "https://status.npmjs.org/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://static-production.npmjs.com/b0f1a8318363185cc2ea6a40ac23eeb2.png",
  },
  {
    name: "Docker Hub",
    slug: "docker",
    category: "Developer Tools",
    statusPageUrl: "https://www.dockerstatus.com",
    apiEndpoint: "https://www.dockerstatus.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://www.docker.com/favicon.ico",
  },
  {
    name: "HashiCorp",
    slug: "hashicorp",
    category: "Developer Tools",
    statusPageUrl: "https://status.hashicorp.com",
    apiEndpoint: "https://status.hashicorp.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://www.google.com/s2/favicons?domain=hashicorp.com&sz=64",
  },
  {
    name: "Linear",
    slug: "linear",
    category: "Developer Tools",
    statusPageUrl: "https://linearstatus.com",
    apiEndpoint: "https://linearstatus.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://linear.app/favicon.ico",
  },

  // --- Search ---
  {
    name: "Algolia",
    slug: "algolia",
    category: "Search",
    statusPageUrl: "https://status.algolia.com",
    apiEndpoint: "https://status.algolia.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://www.algolia.com/favicon.ico",
  },
  {
    name: "LaunchDarkly",
    slug: "launchdarkly",
    category: "Search",
    statusPageUrl: "https://status.launchdarkly.com",
    apiEndpoint: "https://status.launchdarkly.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://www.google.com/s2/favicons?domain=launchdarkly.com&sz=64",
  },

  // --- Support & CRM ---
  {
    name: "Intercom",
    slug: "intercom",
    category: "Support & CRM",
    statusPageUrl: "https://status.intercom.com",
    apiEndpoint: "https://status.intercom.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://www.intercom.com/intercom-marketing-site/favicons/favicon.ico",
  },
  {
    name: "Zendesk",
    slug: "zendesk",
    category: "Support & CRM",
    statusPageUrl: "https://status.zendesk.com",
    apiEndpoint: "https://status.zendesk.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://d1eipm3vz40hy0.cloudfront.net/images/logos/zendesk-favicon.ico",
  },
  {
    name: "HubSpot",
    slug: "hubspot",
    category: "Support & CRM",
    statusPageUrl: "https://status.hubspot.com",
    apiEndpoint: "https://status.hubspot.com/api/v2/summary.json",
    sourceType: "STATUSPAGE_API",
    logoUrl: "https://www.hubspot.com/favicon.ico",
  },
];

export const CATEGORIES = [...new Set(services.map((s) => s.category))].sort();
